import { ROLES } from './roles';
import { PERMISSIONS } from './permissions';

export const ROLE_PERMISSIONS = {
  [ROLES.CAJERO]: [
    PERMISSIONS.CAJA_VIEW,
    PERMISSIONS.CAJA_ABRIR,
    PERMISSIONS.CAJA_CERRAR,
    PERMISSIONS.CAJA_ARQUEO,
    PERMISSIONS.CAJA_RESUMEN,
    PERMISSIONS.MAESTROS_CAJAS_VIEW,
    PERMISSIONS.TICKETS_VIEW,
    PERMISSIONS.TICKETS_BUSCAR,
    PERMISSIONS.TICKETS_SIMULAR,
    PERMISSIONS.TICKETS_COBRAR,
    PERMISSIONS.FACTURACION_VIEW,
    PERMISSIONS.FACTURACION_EMITIR,
    PERMISSIONS.CLIENTES_VIEW,
    PERMISSIONS.CLIENTES_BUSCAR,
    PERMISSIONS.CLIENTES_CREAR,
    PERMISSIONS.TURNOS_VIEW
  ],
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CAJA_VIEW,
    PERMISSIONS.CAJA_ABRIR,
    PERMISSIONS.CAJA_CERRAR,
    PERMISSIONS.CAJA_ARQUEO,
    PERMISSIONS.CAJA_RESUMEN,
    PERMISSIONS.CAJA_GESTION,
    PERMISSIONS.CAJA_CIERRE_FORZADO,
    PERMISSIONS.MAESTROS_CAJAS_VIEW,
    PERMISSIONS.TICKETS_VIEW,
    PERMISSIONS.TICKETS_BUSCAR,
    PERMISSIONS.TICKETS_SIMULAR,
    PERMISSIONS.TICKETS_COBRAR,
    PERMISSIONS.FACTURACION_VIEW,
    PERMISSIONS.FACTURACION_EMITIR,
    PERMISSIONS.CLIENTES_VIEW,
    PERMISSIONS.CLIENTES_BUSCAR,
    PERMISSIONS.CLIENTES_CREAR,
    PERMISSIONS.CLIENTES_EDITAR,
    PERMISSIONS.TARIFAS_VIEW,
    PERMISSIONS.TURNOS_VIEW,
    PERMISSIONS.TURNOS_MANAGE,
    PERMISSIONS.REPORTES_VIEW,
    PERMISSIONS.REPORTES_CIERRE_CAJA
  ],
  [ROLES.ADMINISTRADOR]: Object.values(PERMISSIONS)
};
